---
jobs:
- name: docker_trigger
  plan:
  - task: docker_trigger
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: docker
        args: ["--version"]
